<a href="https://colab.research.google.com/github/tajuar-akash-hub/Machine-learning-algorithms/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# why numpy?
1 ) numpy is fast than list
2) Element stored in conguous memory location
3) its a MATLAB replacement
4) can store images!

#Create an numpy array

In [ ]:
import numpy as np

In [ ]:
a = np.array(
    [1,2,3,4,5]
)

In [ ]:
a

array([1, 2, 3, 4, 5])

# 2D array

In [ ]:
b = np.array([ [1,2,3,4],[5,6,7,8] ] )
b


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 3D array

In [ ]:
c = np.array(
    [  [ [1,2,3,4,5] ]  ]
)

In [ ]:
print(c.shape)

(1, 1, 5)


# Get Dimension


In [ ]:
print(a.ndim)
print(b.ndim)

1
2


# Get Shape

In [ ]:
print(a.shape)
print(b.shape)

(5,)
(2, 4)


# Get type

In [ ]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


# zero

In [ ]:
zero = np.zeros( (2,3) )
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

#random

In [ ]:
random = np.random.random( (2,3) )
random

array([[0.19146245, 0.20978234, 0.82656233],
       [0.3894867 , 0.1464109 , 0.98479732]])