<a href="https://colab.research.google.com/github/tajuar-akash-hub/Machine-learning-algorithms/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# why numpy?
1 ) numpy is fast than list
2) Element stored in conguous memory location
3) its a MATLAB replacement
4) can store images!

# Shallow Copy and Deep copy In Pthoin

In [47]:
a = [1,2,3,4]

b = a

In [41]:
#change the value of b

b[0] = 99

In [45]:
print(a)
print(b)

[99, 2, 3, 4]
[99, 2, 3, 4]


## Deep copy

In [53]:
import copy

a = [1,2,3,4]

c = copy.deepcopy(a)   #a stays the same, but c changes

#change something
c[0] = "changed"

print(c)
print(a)


['changed', 2, 3, 4]
[1, 2, 3, 4]


In [35]:
#change c
c = 99

In [37]:
b

99

# shallow copy


In [55]:
a = [1,2,3,4]

d = a.copy()

#change it

d[0] = "changed"

print(d)
print(a)

['changed', 2, 3, 4]
[1, 2, 3, 4]


Note : the real difference is noticeable when we you nested list

In [4]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
b = a[:5]
b

array([0, 1, 2, 3, 4])

In [7]:
b[0:5] = 99   #shallow copy


In [10]:
b

array([99, 99, 99, 99, 99])

In [18]:
c = np.arange(11)
d = c[:5].copy()  #deep copy
d[:5] = 99

array([99, 99, 99, 99, 99])

#Create an numpy array

In [2]:
import numpy as np

In [ ]:
a = np.array(
    [1,2,3,4,5]
)

In [ ]:
print(a)

1 2 3 4 5


# 2D array

In [ ]:
b = np.array([ [1,2,3,4],[5,6,7,8] ] )
b


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 3D array

In [ ]:
c = np.array(
    [  [ [1,2,3,4,5] ]  ]
)

In [ ]:
print(c.shape)

(1, 1, 5)


# Get Dimension


In [ ]:
print(a.ndim)
print(b.ndim)

1
2


# Get Shape

In [ ]:
print(a.shape)
print(b.shape)

(5,)
(2, 4)


# Get type

In [ ]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


# zero

In [ ]:
zero = np.zeros( (2,3) )
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

# Ones

In [ ]:
one = np.ones( (2,3)  )
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


# Arrange

In [ ]:
arrange = np.arange( 10 )
arrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10,20,2) # Start , end, step

array([10, 12, 14, 16, 18])

# LinSpace

In [ ]:
np.linspace(0,10,num=5)  # range 0 to 10, total value 5, and their differnce is same

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#random

In [ ]:
random = np.random.random( (2,3) )
random

array([[0.19146245, 0.20978234, 0.82656233],
       [0.3894867 , 0.1464109 , 0.98479732]])

# Random vs Rand

In [ ]:
a = np.random.random( (2,3)  )  #random with shape change
print(a)

[[0.75879762 0.49230191 0.3575513 ]
 [0.3651551  0.04066659 0.86074186]]


# RandInt

In [10]:
np.random.randint(low = 0, high= 10 , size =(10,10) )

array([[9, 3, 7, 2, 9, 4, 7, 4, 6, 4],
       [2, 2, 0, 0, 6, 3, 6, 0, 0, 8],
       [9, 2, 7, 8, 9, 7, 1, 4, 3, 0],
       [9, 3, 8, 9, 8, 4, 1, 5, 1, 8],
       [4, 6, 9, 7, 6, 0, 4, 7, 9, 2],
       [7, 9, 3, 5, 5, 8, 2, 4, 3, 8],
       [9, 0, 8, 4, 0, 6, 3, 4, 4, 7],
       [8, 6, 5, 6, 3, 6, 3, 8, 6, 5],
       [9, 7, 7, 8, 6, 8, 7, 4, 4, 6],
       [2, 7, 0, 4, 4, 2, 4, 8, 8, 9]])

In [ ]:
b = np.random.rand( 2,3  )  # for rand, don't have to provide tuple as a parameter
print(a)

[[0.75879762 0.49230191 0.3575513 ]
 [0.3651551  0.04066659 0.86074186]]


#  Numpy Value Access

In [ ]:
ar = np.array( [1,2,3,34,5] )
print(ar)

#access certain elements
print( ar[3] )

[ 1  2  3 34  5]
34


In [ ]:
ar1 = np.array( [ [1,2,3,34,5], [5,6,7,8,9] ] )

print(ar[1][4])



9


# Slicing

In [ ]:
print(ar[:3])

[1 2 3]


# Sort

In [ ]:
a = np.array([10,11,12,13,14,15])
np.sort(a)

array([10, 11, 12, 13, 14, 15])

# Reshpae

In [ ]:
a = np.array([10,11,12,13,14,15])
a.reshape(2,3)

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
# Single line
print(np.array( [10,20,30,40] ).reshape(2,2))

[[10 20]
 [30 40]]


In [ ]:
# Undo dimension

In [ ]:
a.ravel()

array([10, 11, 12, 13, 14, 15])

# Difference between Faltten and Ravel

In [15]:
temp = np.random.random(10).reshape(5,2)
temp

array([[0.67019249, 0.78949832],
       [0.04987518, 0.98097219],
       [0.21278648, 0.04285792],
       [0.21836328, 0.72940914],
       [0.22017948, 0.99787959]])

# Append

In [22]:
a = np.arange(20).reshape(10,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [23]:
another_array = [100,200]
np.append(a,another_array)  #problem is it will make it one dimensioanl again

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 100, 200])

In [16]:
temp.flatten()  # extra theory to understand, shallow copy, deep copy , flatten is deep copy

array([0.67019249, 0.78949832, 0.04987518, 0.98097219, 0.21278648,
       0.04285792, 0.21836328, 0.72940914, 0.22017948, 0.99787959])

# Dot product

In [ ]:
a = np.array(
    [
        [1,2],
        [3,4]
    ]
)

b = np.array(
    [
        [0,1],
        [1,0]
    ]
)

dot = np.dot(a,b)
print(dot)

[[2 1]
 [4 3]]


# Transpose matrix (row to column, column to row)

In [ ]:
trans = np.arange(10).reshape(5,2)
print(trans)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
trans.transpose()

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

# Max ,Min

In [ ]:
a = np.array([1,2,3,4,5,6])

print(a.max())
print(a.min())
print(a.sum())

6
1
21


# Axis wise sum

In [ ]:
c = np.arange(12).reshape(3,4)

print(c)

print("result of axis = 0 ")
print(c.sum(axis=0))  # summing all columns


print("result of axis = 1 ")
print(c.sum(axis=1))  # summing all columns

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
result of axis = 0 
[12 15 18 21]
result of axis = 1 
[ 6 22 38]


In [ ]:
np.random.random(10).reshape(2,5)

array([[0.04412408, 0.85869139, 0.83316977, 0.01428163, 0.42071867],
       [0.9649462 , 0.09764058, 0.00156086, 0.09082053, 0.57544386]])

# Arg Max

In [ ]:
random = np.random.random(10)
random

array([0.69363035, 0.2464375 , 0.80472158, 0.13715147, 0.59506715,
       0.58940823, 0.30558477, 0.43941469, 0.48179924, 0.31507338])

In [ ]:
print(random.max())  #only the maximum value
print(random.argmax())  # Maximum value with index

0.804721575141959
2


# Full

In [11]:
np.full( [5,5] , 7, dtype=int )

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

# Ideantical matrix

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Printing technique


In [36]:
array1 = np.array( (1,2,3,4,5) )
array2 = np.array( (5,6,7,8,9) )


a = np.array([array1,array2])
a

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [34]:
#print

print(array1[0])

#structure array[row,column]
print(a[0,0])  #here row = 0, column = 0


#print 4, 5
      # 8, 9

1
1
[[4]]


In [38]:
print(a[0:2,3:5])

[[4 5]
 [8 9]]
